Repository lookit/lookit-api, pull requests merged in 2019-08, with the labels that each got.

#312 Query DSL replacing EligibilityModel workflow
  Pipfile
  Pipfile.lock
  accounts/forms.py
  accounts/models.py
  accounts/queries.py
  accounts/tests.py
  requirements/defaults.txt
  studies/fields.py
  studies/forms.py
  studies/migrations/0051_eligibility_criteria_expression_support.py
  studies/models.py
  studies/templates/studies/_study_fields.html
  studies/templates/studies/study_detail.html
  studies/templates/studies/study_participant_eligibility.html
  web/templates/web/study-detail.html
  web/templatetags/__init__.py
  web/templatetags/web_extras.py
Labels: Researcher, researcher usability

#311 Study History contains downloadable session videos
  attachment_helpers.py
  web/templates/web/studies-history.html
  web/views.py
Labels: Participant

#317 reappropriating date_modified as s3 timestamp
  studies/migrations/0052_add-s3-timestamp.py
  studies/models.py
  web/views.py
Labels: Participant

#318 Feature/138 feedback tool
  Pipfile
  Pipfile.lock
  exp/views/study.py
  requirements/defaults.txt
  studies/templates/studies/study_responses.html
Labels: Researcher

#320 Allow empty expressions
  accounts/queries.py
Labels: Researcher

#324 Preclude meaningless getter call by forcing non-null/undefined value
  studies/templates/studies/study_responses_consent_ruling.html
Labels: bug

#315 Feature/310 add invoke tasks for development
  .gitignore
  Pipfile
  Pipfile.lock
  project/settings/defaults.py
  tasks.py
Labels: Developer

#325 Deprecate old eligibility view
  exp/urls.py
  exp/views/study.py
  studies/forms.py
  studies/migrations/0053_deprecate-old-eligiblity-form.py
  studies/models.py
Labels: Researcher

#327 Fix dev build + cleanup
  Pipfile
  Pipfile.lock
  project/settings/defaults.py
  requirements/defaults.txt
  tasks.py
Labels: Developer, critical

#329 Bugfix/pr 328 cleanup
  studies/forms.py
  studies/templates/studies/study_edit.html
  web/templates/web/studies-history.html
Labels: aesthetic

#331 Bugfix/pr 328 cleanup
  accounts/migrations/0043_gestational-age-can-be-blank.py
  accounts/models.py
  web/templates/web/study-detail.html
Labels: aesthetic, bug
